# Generated by Django 2.2.7 on 2019-11-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy', models.CharField(choices=[('UG', 'Under graduate'), ('PG', 'Post graduate'), ('Ph.D', 'Doctorate')], default='UG', max_length=5)),
            ],
        ),
    ]
