# Generated by Django 2.2.7 on 2019-12-08 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=10, null=True)),
                ('suffix', models.CharField(max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('sur_name', models.CharField(max_length=30, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contacts.User')),
                ('company_name', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('description', models.TextField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contacts.User')),
                ('picture', models.FilePathField(verbose_name='/home/sethuraman/Documents/Learn/Django/learndjango')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relation', models.CharField(choices=[('Assistant', 'Assistant'), ('Brother', 'Brother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Friend', 'Friend'), ('Manager', 'Manager'), ('Partner', 'Partner'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Relative', 'Relative')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contacts.User')),
            ],
        ),
        migrations.CreateModel(
            name='MobileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(choices=[('M', 'Mobile'), ('W', 'Work'), ('H', 'Home'), ('O', 'Office')], default='M', max_length=10)),
                ('email', models.CharField(max_length=50, null=True)),
                ('email_type', models.CharField(choices=[('W', 'Work'), ('H', 'Home')], default='W', max_length=10)),
                ('address', models.TextField(max_length=150, null=True)),
                ('address_type', models.CharField(choices=[('W', 'Work'), ('H', 'Home')], default='W', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.User')),
            ],
        ),
        migrations.CreateModel(
            name='DateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.User')),
            ],
        ),
    ]
