# Generated by Django 2.2.7 on 2019-12-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileinfo',
            name='contact',
            field=models.IntegerField(default=1234567890),
        ),
    ]
