# Generated by Django 2.2.7 on 2019-12-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_mobileinfo_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileinfo',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
