# Generated by Django 2.2.7 on 2019-11-19 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20191119_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(choices=[('M', 'Mobile'), ('W', 'Work'), ('H', 'Home'), ('O', 'Office')], max_length=10)),
                ('email', models.CharField(choices=[('W', 'Work'), ('H', 'Home')], max_length=10)),
                ('address', models.CharField(choices=[('W', 'Work'), ('H', 'Home')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.User')),
            ],
        ),
    ]
