# Generated by Django 2.2.7 on 2019-11-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_mobileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('description', models.TextField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contacts.User')),
                ('picture', models.FilePathField(verbose_name='/home/sethuraman/Documents/Learn/Django/learndjango')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relation', models.CharField(choices=[('Assistant', 'Assistant'), ('Brother', 'Brother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Friend', 'Friend'), ('Manager', 'Manager'), ('Partner', 'Partner'), ('Sister', 'Sister'), ('Spouse', 'Spouse'), ('Relative', 'Relative')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contacts.User')),
            ],
        ),
        migrations.CreateModel(
            name='DateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occasion', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.User')),
            ],
        ),
    ]
